openapi: 3.0.3
info:
  title: Holiday Booking API
  description: |-
    This is documentation for an endpoint to book holidays.
    
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
tags:
  - name: holidays
    description: Everything about booking holidays
  - name: user
    description: Operations about user
paths:
  /get_remaining_holidays/{email}:
    get:
      tags:
        - user
        - holidays
      description: Get remaining holidays for a user
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: integer
                example: 27
        '404':
          description: User not found
  /reduce_remaining_holidays/{email}/{days}:
    get:
      tags:
        - user
        - holidays
      description: Reduces a users remaining holidays by X days
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
        - name: days
          in: path
          description: Number of days to reduce the users holidays by
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '302':
          description: 'redirect user to /get_remaining_holidays/{email}'
        '404':
          description: 'User not found'
    post:
      tags:
        - user
        - holidays
      description: Reduces a users remaining holidays by X days
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
        - name: days
          in: path
          description: Number of days to reduce the users holidays by
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '201':
          description: 'No content'
        '404':
          description: 'User not found'
  /reset_remaining_holidays/{email}:
    get:
      tags:
        - user
        - holidays
      description: Resets users holiday allowance to default
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
      responses:
        '302':
          description: 'redirect user to /get_remaining_holidays/{email}'
        '404':
          description: 'User not found'
    post:
      tags:
        - user
        - holidays
      description: Resets users holiday allowance to default
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
      responses:
        '201':
          description: 'No content'
        '404':
          description: 'User not found'
  /book_holiday/{email}/{date}:
    post:
      tags:
        - user
        - holidays
      description: Books a day as a holiday
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
        - name: date
          in: path
          description: Date to book off
          required: true
          schema:
            type: string
            format: date
            example: '2023-08-01'
      responses:
        '201':
          description: 'No content'
        '400':
          description: 'database is locked'
  /get_name/{email}:
    get:
      tags:
        - user
      description: Gets the username for a given email
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
      responses:
        '200':
          description: Username of email
          content:
            text/plain:
              schema:
                type: string
                example: testuser
        '404':
          description: User not found
  /get_holidays/{email}:
    get:
      tags:
        - user
        - holidays
      description: Get all holidays booked for a given email
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
            example: 'test.user@domain.com'
      responses:
        '200':
          description: Username of email
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: string
                  format: date
        '404':
          description: User not found